### ISSUE TITLE
Lost discussion and need to reload pages

### ISSUE THREAD

**Issue by kinnehora** [zooniverse/Radio-Galaxy-Zoo#137]
If you "search" on J084017.83 +175722.7 you get different results when you try the thing more than once. Sometimes it links to 
http://radiotalk.galaxyzoo.org/#/boards/52b0abed2b60f1689b000016/discussions/DRG00004qk (which is a different place), sometimes it links to 
  http://radiotalk.galaxyzoo.org/#/boards/BRG0000005/discussions/DRG00004qk
which is the right place.

This may be connected with multiple problems with things not working, pages going blank when you click links, submit button doing nothing except fading when you  click it, etc., all fixed by reloading page.
Using Mac OSX 10.9.4 and Firefox 32.0.2

**Comment by edpaget** [comment]
Talk issue: https://github.com/zooniverse/Talk/issues/135
