### ISSUE TITLE
Users reporting "crashing"; blank image in browser

### ISSUE THREAD

**Issue by willettk** [zooniverse/Radio-Galaxy-Zoo#147]
One of our most prolific RGZ users (```antikodon```) is reporting repeated "crashes" in his browser while classifying. Symptoms seem to be:

- neither IR image nor contours appearing in the container
- classification buttons appear multiple times on the screen
- screenshot below

![41104350437044b043c044f043d043d044b04390_zpsadfaf723](https://cloud.githubusercontent.com/assets/2285931/5925303/2af11312-a628-11e4-9091-2a80603e6471.jpg)

They report no issues if they use a different Zooniverse account, but I very much want them to stay with this account since that'll screw up data reduction and weighting for specific users. 

At least one instance started on 20 Jan 2015 at 12h00 (not sure of timezone), using Chrome 40.0.2214.91.

**Comment by edpaget** [comment]
Kyle do you think you could ask him/her for a dump of their browser's console? https://developer.chrome.com/devtools/docs/console

**Comment by willettk** [comment]
Good idea. I'll ask.

**Comment by vrooje** [comment]
How prolific? They couldn't be out of subjects, right?

**Comment by edpaget** [comment]
Yeah that's kind of what I was thinking.

**Comment by willettk** [comment]
Shouldn't be - I checked that once before, and they hadn't done enough for
that to have been the issue. I think Zooniverse is supposed to display a
"No subjects available" message if they do run out, rather than a blank
screen.

**Comment by edpaget** [comment]
I'm not sure if RGZ does that. I dont' have a good enough internet connection at the moment to login to mongo, but I'll check as soon as I do.

**Comment by willettk** [comment]
Report from the user in question: 

The only thing that shows output GET http://radio.galaxyzoo.org/js/app.js.map 404 (Not Found)

**Comment by edpaget** [comment]
@willettk sorry this took me so long to get back around to. The 'antikodon' has classified all the available subjects. I'll add a message that'll get displayed for users who are out of subjects.

**Comment by willettk** [comment]
Huh - didn't know we had anyone at that level.

I hate telling users "come back later, you've done them all". What are the
pros/cons for increasing the size of the active pool?

**Comment by edpaget** [comment]
The server that handles selecting subjects for classification needs to be able to hold the active subjects for all projects and the seen subjects for all active users in memory. Do you have any talk-based talks you could ask the user to do?

**Comment by willettk** [comment]
Maybe - that's a good suggestion.

Do you know what our average retirement rate/day is for RGZ? Curious what
the average number of "new" classifications that this person could do is.

**Comment by edpaget** [comment]
Sorry I'm not sure how quick this are getting retired. It looks like you're getting between 500-1200 classifications a day, so it definitely could be a few.
