### ISSUE TITLE
New Bug in RGZ Tutorial. Please fix ASAP 

### ISSUE THREAD

**Issue by ivyw** [zooniverse/Radio-Galaxy-Zoo#149]
Hi Chris,

The tutorial dies after the 2nd step. Just got a phone call from the ABC Science reporter saying that RGZ is down and they can't make head or tail of the project because the links and buttons only work half the time.  Also due to the tutorial disappearing after the 2nd step, the new users are all left very confused.  

Any help is much appreciated.
cheers,
Ivy

**Comment by edpaget** [comment]
The tutorial should be fixed now. I'm not sure about the other problems @chrissnyder if you get a chance to look.

**Comment by chrissnyder** [comment]
Ivy,

Are there any more specifics on what is causing the site to break? Tried a couple classifications here and it seems to be working properly.

**Comment by ivyw** [comment]
The issue with the contours appear to have gone away so it was probably linked to the bug affecting the tutorial.

Thanks heaps again Ed & Chris!
