### ISSUE TITLE
Change ratio of ATLAS/FIRST subjects

### ISSUE THREAD

**Issue by willettk** [zooniverse/Radio-Galaxy-Zoo#152]
Given the smaller sample size of the ATLAS subjects, the science team would like to prioritize finishing those ahead of the much larger FIRST sample. Can we increase the ratio of ATLAS to FIRST subjects, similar to the way that grouping is done for Galaxy Zoo? https://github.com/zooniverse/Galaxy-Zoo/blob/c11afb1b9c3e105d807422c6fba9baa3c649ec4e/app/models/subject.coffee#L53

**Comment by chrislintott** [comment]
This might be best handled by @parrish - Michael, what do you think?

**Comment by parrish** [comment]
It's not a grouped project, but I could make it grouped.  That would allow the frontend to specify the ratios of selection (like Galaxy Zoo).

I'll pick it up early next week.

**Comment by willettk** [comment]
Grouping them would be fine by me; I already have to hack them when I import the BSON files to add a "survey" field. Grouping them would make it simpler. 

```python
subjects.update({'metadata.source':re.compile("^C",re.IGNORECASE)},{'$set':{'metadata.survey':'atlas'}},multi=True)
subjects.update({'metadata.source':re.compile("^FIRST",re.IGNORECASE)},{'$set':{'metadata.survey':'first'}},multi=True)
```

**Comment by parrish** [comment]
Done.  I also added the survey to the subject metadata.

**Comment by willettk** [comment]
Thanks, @parrish. Could you give me an example of how to select from the groups at a given ratio? Something like in https://github.com/zooniverse/Galaxy-Zoo/blob/056cb0ccc15f38514f5bb6a751cb603a0742458d/app/models/subject.coffee#L60

**Comment by parrish** [comment]
Right now it's at 50% selection rate for each group.  Atlas only has 1050 classifications to be completed -- which should be done by tomorrow.  Unless we plan on adding more data, I probably wouldn't worry about it.  If you're still curious (or really don't want it to finish that quickly), I could send a PR with the changes for it.

**Comment by willettk** [comment]
Wow - that's much less than I'd thought. Totally fine as is, if that's the
case.

**Comment by willettk** [comment]
Hey @parrish - I'm wondering if the retirement rate for the ATLAS subjects is properly set. I looked at the classification counts so far, and they all seem to be stopping at 5 classifications apiece. 

![atlas_classification_counts](https://cloud.githubusercontent.com/assets/2285931/9862154/aa9896e2-5afc-11e5-9423-7c0317b4b85c.png)

The FIRST subjects are set so that if `metadata.contour_count : 1`, the subject is retired after only 5 classifications (since the task is much simpler). More complicated subjects with `metadata.contour_count : {$gte : 2}` are retired at 20.

None of the ATLAS subjects have `contour_count` in the metadata, though, so it seems that most ATLAS sources that are being prematurely retired (only 5% have just 1 radio component, according to the contour data). Does that agree with what you know?

**Comment by parrish** [comment]
> None of the ATLAS subjects have contour_count in the metadata

Yep.  Since they don't have a contour count, they're retired at 5.

**Comment by willettk** [comment]
K. Can we change that? We really do need more than 5 clicks for the
majority of ATLAS subjects. We can start analyzing the data we have, but
it's not usually enough to provide consensus.

I think we'd need:

- contour_count added to the ATLAS subjects
- reactivate any subjects with contour_count > 1 and classification_count >
20
- keep running with the 50/50 ATLAS/FIRST ratio and the same retirement
rules?

Is that possible, @parrish? Anything I can do to help?

**Comment by parrish** [comment]
Sure, if you have the contour counts handy, that'd certainly be helpful.  Otherwise, I can pull them from the JSON files.

**Comment by willettk** [comment]
Voici: https://www.dropbox.com/s/5pm8arp18t5m07i/atlas_contour_counts.csv?dl=0

**Comment by parrish** [comment]
Done!

**Comment by willettk** [comment]
Thanks, Michael!
